//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEğitimKampiEFProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EgitimKampiEFTravelDbEntities : DbContext
    {
        public EgitimKampiEFTravelDbEntities()
            : base("name=EgitimKampiEFTravelDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBLCustomer> TBLCustomers { get; set; }
        public virtual DbSet<TBLGuide> TBLGuides { get; set; }
        public virtual DbSet<TBLLocation> TBLLocations { get; set; }
        public virtual DbSet<TBLAdmin> TBLAdmins { get; set; }
    }
}
